---
# This playboot use rhel system role 
#  to set selinux  boolean 
- hosts: webservers
  become: yes
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
    selinux_booleans:
      - { name: 'httpd_can_network_connect', state: 'on', persistent: 'yes' }
  roles:
    - rhel-system-roles.selinux


--- 
